/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:words:644026:
  println("words - GTextArea >> GEvent." + event + " @ " + millis());
} //_CODE_:words:644026:

public void btnSing_click(GButton source, GEvent event) { //_CODE_:btnSing:699576:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:btnSing:699576:

public void stick1_change1(GStick source, GEvent event) { //_CODE_:stick1:415184:
  println("stick1 - GStick >> GEvent." + event + " @ " + millis());
} //_CODE_:stick1:415184:

public void knob1_turn1(GKnob source, GEvent event) { //_CODE_:knob1:672781:
  println("knob1 - GKnob >> GEvent." + event + " @ " + millis());
} //_CODE_:knob1:672781:

public void timer1_Action1(GTimer source) { //_CODE_:timer1:595166:
  println("timer1 - GTimer >> an event occured @ " + millis());
} //_CODE_:timer1:595166:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.RED_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("i, mitniq");
  words = new GTextArea(this, 9, 6, 291, 160, G4P.SCROLLBARS_BOTH | G4P.SCROLLBARS_AUTOHIDE);
  words.setText("hi");
  words.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  words.setOpaque(true);
  words.addEventHandler(this, "textarea1_change1");
  btnSing = new GButton(this, 309, 8, 80, 30);
  btnSing.setText("SING");
  btnSing.addEventHandler(this, "btnSing_click");
  stick1 = new GStick(this, 313, 67, 60, 60);
  stick1.setMode(G4P.X4);
  stick1.setOpaque(false);
  stick1.addEventHandler(this, "stick1_change1");
  knob1 = new GKnob(this, 387, 65, 60, 60, 0.8);
  knob1.setTurnRange(110, 70);
  knob1.setTurnMode(GKnob.CTRL_HORIZONTAL);
  knob1.setSensitivity(1);
  knob1.setShowArcOnly(false);
  knob1.setOverArcOnly(false);
  knob1.setIncludeOverBezel(false);
  knob1.setShowTrack(true);
  knob1.setLimits(0.5, 0.0, 1.0);
  knob1.setShowTicks(true);
  knob1.setOpaque(false);
  knob1.addEventHandler(this, "knob1_turn1");
  timer1 = new GTimer(this, this, "timer1_Action1", 1000);
}

// Variable declarations 
// autogenerated do not edit
GTextArea words; 
GButton btnSing; 
GStick stick1; 
GKnob knob1; 
GTimer timer1; 
